### ISSUE TITLE
server error as of 5.0

### ISSUE THREAD

**Issue by nwolverson** [purescript-contrib/pulp#113]
(Incidentally the latest release on npm is 5.0 but the last git release is 4.5)

With 5.0.0 I get install warnings along the lines of:

```
npm WARN installMany abbrev was bundled with bower@1.6.6, but bundled package wasn't found in unpacked tree
```

Some commands work, but for `pulp server` I get the following:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'touch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pulp/server.js:3:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by nwolverson** [comment]
Actually I get the same warnings with the earlier version install but (with 4.5.0) `pulp server` works
