### ISSUE TITLE
Error with pulp init

### ISSUE THREAD

**Issue by shubh1m** [purescript-contrib/pulp#277]
Error while doing pulp init.

`
> pulp init
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/purescript/vendor/purs ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
* ERROR: Subcommand terminated with exit code 1
`

**Comment by hdgarrood** [comment]
Is the `bower` executable on your path? What happens if you try `pulp init` and then, after it fails, run `bower install --save purescript-prelude purescript-console`?

**Comment by shubh1m** [comment]
Hi @hdgarrood . Thanks for your quick reply :+1:   
After trying many things, the problem fixed just by installing purescript again using   
`sudo npm install -g purescript`.
