### ISSUE TITLE
Platform detection fails on OpenBSD, prevents pulp from starting

### ISSUE THREAD

**Issue by AlexanderAA** [purescript-contrib/pulp#299]
Platform detection fails on OpenBSD, prevents pulp from starting

Specifically, this line in /usr/local/lib/node_modules/pulp/pulp.js fails:

```
var platform = Data_Maybe.fromJust()Node_Platform.fromString($foreign.process.platform))
```

Error happens because ```Node_Platform.fromString($foreign.process.platform)``` returns 
Nothing. (See https://github.com/purescript-node/purescript-node-process/edit/master/src/Node/Platform.purs)

Error log:
```
/usr/local/lib/node_modules/pulp/pulp.js:2360
              throw new Error("Failed pattern match at Data.Maybe line 271, column 1 - line 271, column 21: " + [ v.constructor.name ]);
                             ^

Error: Failed pattern match at Data.Maybe line 271, column 1 - line 271, column 21: Nothing
    at /usr/local/lib/node_modules/pulp/pulp.js:2360:36
    at /usr/local/lib/node_modules/pulp/pulp.js:2361:13
    at PS.Node.Process (/usr/local/lib/node_modules/pulp/pulp.js:13659:39)
    at Object.<anonymous> (/usr/local/lib/node_modules/pulp/pulp.js:13700:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by AlexanderAA** [comment]
I believe, this is not exactly a pulp issue, but just something to account for. The corresponding external function can return `undefined` on some platforms. 

```
$ node
> console.log(`This platform is ${process.platform}`);
This platform is openbsd
undefined
```

**Comment by hdgarrood** [comment]
Thanks for the report!
