### ISSUE TITLE
Error in (successful) CI build log

### ISSUE THREAD

**Issue by nwolverson** [purescript-contrib/pulp#355]
In passing CI builds (eg [current master](https://travis-ci.org/purescript-contrib/pulp/builds/389773050)) there's a nasty looking stacktrace, I wonder if there's a problem with the travis config or something about `psvm`.

```
>> psvm use v0.11.6
Switching to PureScript : v0.11.6
Unhandled rejection TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.unlink (fs.js:1036:14)
    at /home/travis/build/purescript-contrib/pulp/node_modules/psvm/src/lib.js:90:31
    at _map (/home/travis/build/purescript-contrib/pulp/node_modules/ramda/dist/ramda.js:376:27)
    at /home/travis/build/purescript-contrib/pulp/node_modules/ramda/dist/ramda.js:3919:23
    at Object.f2 [as map] (/home/travis/build/purescript-contrib/pulp/node_modules/ramda/dist/ramda.js:191:24)
    at /home/travis/build/purescript-contrib/pulp/node_modules/psvm/src/lib.js:89:19
    at tryCatcher (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/purescript-contrib/pulp/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5
```

**Comment by hdgarrood** [comment]
Perhaps it's worth switching to [install-purescript](https://www.npmjs.com/package/install-purescript) instead, which is what the purescript npm package is based on, and is therefore quite a bit more battle-tested.

**Comment by hdgarrood** [comment]
As of #369 we aren't using psvm any more, so I think this can be closed.
