### ISSUE TITLE
`pulp --psc-package init` fails on Windows

### ISSUE THREAD

**Issue by luochen1990** [purescript-contrib/pulp#356]
```
$ pulp --psc-package init --force
* Generating project skeleton in C:\Users\xxx\Test\purescript-test2
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\dev\nvm\v10.4.1\node_modules\psc-package\vendor\psc-package.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
* ERROR: Subcommand terminated with exit code 1
```

It seems you should call `psc-package.cmd` instead of `psc-package.exe`.

**Comment by nwolverson** [comment]
Worth noting the `psc-package` node package [is deprecated](https://github.com/joneshf/node-psc-package-bin)

**Comment by luochen1990** [comment]
hmmm, I use this command since there is an [article](https://qiita.com/kimagure/items/570e6f2bbce5b4724564) named "Setting up PureScript in March 2018" .
Since both psc-package and bower are deprecated,  what is the recommended way to use purescript in 2018 ?

**Comment by natefaubion** [comment]
`psc-package` is not deprecated, only the node/npm wrapper script.

**Comment by hdgarrood** [comment]
Looking at https://github.com/purescript/psc-package, it seems like there isn't a supported way of installing `psc-package` which gives you the `.cmd` suffix, so I think this can be closed.
