### ISSUE TITLE
Deleted/renamed modules are retained in output/ causing false positives

### ISSUE THREAD

**Issue by damncabbage** [purescript-contrib/pulp#56]
Output from `pulp build`/`pulp run` appears to be being inappropriately retained; changing module names (or removing modules entirely) and then `pulp run`-ing or `build`-ing the project still produces the same result, as if the rename/delete had never happened, until the module's `output/ModuleNameHere/` cache files are manually removed.

To reproduce:

``` bash
$ pulp init
$ pulp run
...
Hello sailor!

## Rename the module file and definition. Just running "rm src/Main.purs"
## produces the same result below.
$ mv src/Main.purs src/NotMain.purs
$ sed -i ''  -e 's/module Main/module NotMain/g' src/NotMain.purs

$ pulp run
...
Hello sailor!

$ rm -rf output/Main
$ pulp run
* Building project in /Users/damncabbage/example
* Build successful.
module.js:338
    throw err;
          ^
Error: Cannot find module 'Main'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/var/folders/dv/x_g...gn/T/pulp-run115...vo.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
* ERROR: Subcommand terminated with error code 1
```

(Pulp version 4.0.2, just installed from npm.)

**Comment by bodil** [comment]
This is a psc issue, not a pulp issue. Nothing pulp can do about it except delete the output directory before every run, which would be rather bad for incremental compilation performance. I'd recommend filing this issue on the main PureScript repo.

**Comment by damncabbage** [comment]
Understood; thanks. :)
